# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medlem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=63)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True)),
                ('contact', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
