# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=255, unique_for_month='pub date')),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Medlem')),
            ],
            options={
                'verbose_name': 'dagbok post',
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
