# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagbok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
