# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-24 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagbok', '0002_auto_20180123_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=255, unique_for_date='date'),
        ),
    ]
